name: create comment on new issue

#on newly created issues
on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        #dumps the github event JSON into the action
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

        #Using a community action, add a comment to the issue number using the github event JSON dump
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          issue-number: '${{ github.event.issue.number }}'
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
          
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST https://api.github.com/repos/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments -f body='Comment but from the API call not action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
